apps/Article/urls.py
from django.urls import path
from . import views

app_name = 'Article'
urlpatterns = [
    path('',views.Article_view, name='Article_view'),
    path('blog/',views.Article_create, name='Article_create'),
    path('article_detaile/<int:id>/',views.article_detaile , name='article_detaile'),
]

apps/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
]

apps/places/urls.py
from django.urls import path
from . import views

app_name = 'places'
urlpatterns = [
    path('history/',views.garden_history ,name='history'),
    path('section/',views.section_list , name='section'),
    path('section_detail/<int:id>/',views.section_detail ,name='section_detail'),
    path('visit_route/', views.visit_route , name = 'visit_route'),
    path('visiting_schedule/',views.visiting_schedule , name = 'visiting_schedule'),
    path('contact_view/',views.contact_view , name = 'contact_view'),

]

apps/workshop/urls.py
from django.urls import path
from . import views

app_name = 'workshop'
urlpatterns = [
    path('workshop_list/',views.workshop_list,name='workshop_list'),
    path('workshop_detaile/<int:id>/',views.workshop_detaile , name='workshop_detaile'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.main.urls', namespace='main'),name='main'),
    path('places/',include('apps.places.urls',namespace='places'),name='places'),
    path('Article/',include('apps.Article.urls',namespace='Article'),name='Article'),
    path('workshop/',include('apps.workshop.urls',namespace = 'workshop'),name ='workshop')
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/partials/header.html
<div class="header">
    <div class="left-group">
        <img src={{media_url}}/images/logo/logo.png  class="logo-circle" alt="Logo">
        <h4>باغ موزه فردوس</h4>
    </div>

</div>

templates/partials/message.html
{% if messages %}
    {% for message in messages %}
    <h5 class="alert alert-{{message.tags}}">{{message}}</h5>
    {% endfor %}
{% endif %}

templates/partials/navbar.html
{%  load static %}
<!doctype html>
<html lang="fa" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Navbar RTL</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.min.css' %}">
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <script src="{% static 'js/jquery-4.0.0.min.js' %}"></script>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'main:index' %}">خانه</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain" aria-controls="navbarMain" aria-expanded="false" aria-label="تغییر منو">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarMain">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <!-- منوی دارای زیرشاخه (dropdown) برای "معرفی باغ" -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle active" href="#" id="aboutDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              معرفی باغ
            </a>
            <ul class="dropdown-menu" aria-labelledby="aboutDropdown">
              <li><a class="dropdown-item" href="{% url 'places:history' %}">تاریخچه</a></li>
              <li><a class="dropdown-item" href="{% url 'places:section' %}">بخش های باغ</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'places:visit_route' %}">مسیر بازدید</a></li>
              <li><a class="dropdown-item" href="{% url 'places:visiting_schedule' %}">شرایط و قوانین</a></li>
            </ul>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">گالری</a>
          </li>
           <li class="nav-item">
            <a class="nav-link" href="#">خاطرات بازدید</a>
          </li>

           <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle active" href="#" id="aboutDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              آموزش و پژوهش
            </a>
            <ul class="dropdown-menu" aria-labelledby="aboutDropdown">
            <li><a class="dropdown-item" href="{% url 'workshop:workshop_list' %}">کارگاه</a></li>
            </ul>
          </li>
          
          <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle active" href="#" id="aboutDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
             مقالات
            </a>
            <ul class="dropdown-menu" aria-labelledby="aboutDropdown">
            <li><a class="dropdown-item" href="{% url 'Article:Article_view' %}">لیست مقاله ها</a></li>
            <li><a class="dropdown-item" href="{% url 'Article:Article_create' %}">ثبت مقاله جدید</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'places:contact_view' %}" tabindex="-1" aria-disabled="true">تماس با ما</a>
          </li>
        </ul>

      </div>
    </div>
  </nav>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/partials/scripts.html
"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.rtl.min.css"

templates/partials/slider.html
{% load static %}
<div id="carouselExampleIndicators" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3" aria-label="Slide 4"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="4" aria-label="Slide 5"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="5" aria-label="Slide 6"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{{media_url}}/images/slider/farm.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{{media_url}}/images/slider/brig.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{{media_url}}/images/slider/jump.jpg" class="d-block w-100" alt="...">
    </div>
        <div class="carousel-item">
      <img src="{{media_url}}/images/slider/river.jpg" class="d-block w-100" alt="...">
    </div>
        <div class="carousel-item">
      <img src="{{media_url}}/images/slider/mountain.jpg" class="d-block w-100" alt="...">
    </div>
        <div class="carousel-item">
      <img src="{{media_url}}/images/slider/car.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>