apps/Article/urls.py
from django.urls import path
from . import views

app_name = 'Article'
urlpatterns = [
    path('',views.Article_view, name='Article_view'),
    path('blog/',views.Article_create, name='Article_create'),
    path('article_detaile/<int:id>/',views.article_detaile , name='article_detaile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.main.urls', namespace='main'),name='main'),
    path('places/',include('apps.places.urls',namespace='places'),name='places'),
    path('Article/',include('apps.Article.urls',namespace='Article'),name='Article'),
    path('workshop/',include('apps.workshop.urls',namespace = 'workshop'),name ='workshop')
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/Article/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime
import os

#---------------------------------------------------save image name with time
def article_image_path(instance, filename):
    now = datetime.now().strftime("%Y%m%d_%H%M%S")
    ext = os.path.splitext(filename)[1]
    new_name = f"{now}{ext}"
    return f"images/blog/{new_name}"

#---------------------------------------------------Author
class Author(models.Model):
    id = models.AutoField(primary_key=True ,verbose_name='کد نویسنده')
    name = models.CharField(max_length=100 , verbose_name='نام')
    family = models.CharField(max_length=100 , verbose_name='نام خانوادگی')
    education = models.CharField(max_length=100 , verbose_name='تحصیلات')
    job_title = models.CharField(max_length=100 , verbose_name='شغل')
    email = models.EmailField(unique=True , verbose_name='ایمیل')
    slug = models.SlugField(unique=True ,verbose_name='slug')
    phone_number = models.CharField(max_length=15 ,blank=True ,  verbose_name='شماره تلفن')
    is_active = models.BooleanField(default=False , verbose_name='وضعیت فعال/غیر فعال')

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'نویسنده'
        verbose_name_plural = 'نویسندگان'
        db_table = 't_Author'

#---------------------------------------------------ArticleGroup
class ArticleGroup(models.Model):
    id = models.AutoField(primary_key=True , verbose_name='کد گروه')
    title = models.CharField(max_length=100 , verbose_name='عنوان گروه')

    def __str__(self):
        return self.title
    
    class  Meta:
        verbose_name = ' گروه مقاله'
        verbose_name_plural = 'گروه مقالات'
        db_table = 't_ArticleGroup'

#---------------------------------------------------Article
class Article(models.Model):
    id = models.AutoField(primary_key=True ,verbose_name='کد مقاله')
    article_group = models.ForeignKey(ArticleGroup , on_delete=models.CASCADE , verbose_name='گروه مقاله')
    title = models.CharField(max_length=200 , verbose_name='عنوان مقاله')
    main_image = models.ImageField(upload_to=article_image_path,verbose_name='تصویر اصلی ')
    author= models.ManyToManyField(Author,related_name='articles',verbose_name='نویسنده')
    slug = models.SlugField(unique=True,max_length=200 ,verbose_name='slug')
    description =models.TextField(verbose_name='متن کوتاه')
    abstract = models.TextField(verbose_name='چکیده مقاله')
    keywords = models.CharField (max_length=100 , verbose_name='کلمات کلیدی')
    pdf_name = models.FileField (upload_to='pdfs/' ,max_length=100 , verbose_name='نام فایل اصلی مقاله')
    register_date = models.DateTimeField(default=timezone.now , verbose_name='تاریخ ثبت')
    publication_date = models.DateTimeField(null=True, blank=True ,verbose_name='تاریخ انتشار')
    update_date = models.DateTimeField(auto_now=True ,verbose_name='تاریخ به روز رسانی')
    number_of_visit = models.IntegerField(default=0,verbose_name='تعداد بازدید')
    is_active = models.BooleanField(default=False , verbose_name='وضعیت فعال/غیر فعال ')    
    

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'
        db_table = 't_Article'

#-------------------------------------------------ArticleGallery 
class ArticleGallery(models.Model):
    id = models.AutoField(primary_key=True ,verbose_name='کد تصویر')
    article = models.ForeignKey(Article , on_delete=models.CASCADE , verbose_name='مقاله')
    name = models.CharField(max_length=200 , verbose_name='نام تصویر')
    image = models.ImageField(upload_to='blog/', verbose_name='تصویر')

    def __str__(self):
        return self.name
    
    class Meta :
        verbose_name = ' مقاله تصویر'
        verbose_name_plural = 'تصاویر مقالات'
        db_table = 't_ArticleGallery'



    
    

apps/Article/forms.py
from django import forms
from .models import Article 


#----------------------------------------ArticleForm
class ArticleForm(forms.ModelForm):
    class Meta :
        model = Article
        fields = ['article_group','title','main_image','author','slug','description', 'slug','keywords','pdf_name','register_date','publication_date','number_of_visit','is_active']

apps/Article/views.py
from django.shortcuts import render , redirect
from .forms import ArticleForm
from .models import Article
from django.core.files.storage import FileSystemStorage
import time
import os
from django.conf import settings



#-------------------------------------------------------Article_view
def Article_view(request):
    article = Article.objects.all()
    context = {
        'Articles' : article,
        'media_url': settings.MEDIA_URL,
    }

    
    return render (request , 'article_app/article.html',context)
    
#-------------------------------------------------------article_detaile
def article_detaile(request,id):
    article_detaile = Article.objects.get(id=id)
    context = {
        'article_detaile': article_detaile
    }
    return render (request , 'article_app/article_detaile.html', context)

#--------------------------------------------------------Article_create
def Article_create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)

        if form.is_valid():
            image = request.FILES.get('main_image')

            # # ساختن نام جدید با زمان
            # timestamp = int(time.time())
            # ext = os.path.splitext(image.name)[1] # پسوند فایل
            # new_name = f'{timestamp}{ext}'

            # بررسی سایز
            if image.size > 100 * 1024:
                return render(request, 'blog_app/create.html', {
                    'form': form,
                    'message': 'سایز تصویر بیش از 100 کیلوبایت است'
                })

            # بررسی نوع فایل
            if image.content_type not in ['image/jpeg', 'image/png']:
                return render(request, 'blog_app/create.html', {
                    'form': form,
                    'message': 'نوع فایل نادرست است'
                })

            form.save()  # Django خودش فایل را ذخیره می‌کند
            return redirect('Article:Article_view')

    else:
        form = ArticleForm()

    return render(request, 'article_app/create.html', {'form': form})

templates/article_app/article.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    لیست مقالات
{% endblock title %}

{% block content %}
    <h3 style="text-align: center;"> لیست مقالات</h3>
    <div class="container">
    <table id="mytable" class="display">
        <thead>
            <tr>
                <th style="text-align: center;">عنوان مقاله</th>
                <th style="text-align: center;">تصویر</th>                
                <th style="text-align: center;">خلاصه متن</th>
                <th style="text-align: center;">نویسندگان</th>
                <th style="text-align: center;">گروه</th>
                <th style="text-align: center;">تاریخ به روز رسانی</th>
                <th style="text-align: center;">تعداد بازدید</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for Article in Articles %}
                <tr>
                    <td>{{ Article.title }}</td>
                    <td>
                        <img src="{{ media_url }}{{ Article.main_image }}" 
                             style="width: 240px; vertical-align: middle; margin: 0 0 0 12px;" 
                             alt="تصویر مقاله">
                    </td>                    
                    <td style="text-align: justify;">{{ Article.description }}</td>
                    <td>
                        {% for writer in Article.author.all %}
                            {{ writer.name }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </td>
                    <td>{{ Article.article_group }}</td>
                    <td>{{ Article.update_date|date:"Y/m/d" }}</td>
                    <td>{{ Article.number_of_visit }}</td>
                    <td>
                        <a href="{% url 'Article:article_detaile' id=Article.id %}" class="btn2">مشاهده جزییات</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>

    <!-- بارگذاری کتابخانه‌های DataTables -->
    <!-- <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css"> -->
    <link rel="stylesheet" href="{% static 'css/dataTables.min.css' %}">
    <!-- <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script> -->
    <script src="{% static 'js/jquery-4.0.0.min.js' %}"></script>
    <!-- <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script> -->
    <script src="{% static 'js/dataTables.min.js' %}"></script>

    <script>
    $(document).ready(function() {
        $('#mytable').DataTable({
            language: {
                // url: '//cdn.datatables.net/plug-ins/1.13.6/i18n/fa.json' // فارسی‌سازی
                url: "{% static 'lang/fa.json' %}"
            },
            pageLength: 10,   // تعداد ردیف‌ها در هر صفحه
            lengthMenu: [5, 10, 25, 50], // گزینه‌های انتخاب تعداد
            ordering: true,   // مرتب‌سازی ستون‌ها
            searching: true   // جستجو در جدول
        });

    });
     </script>
{% endblock content %}

templates/article_app/article_detaile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    جزییات مقالات
{% endblock title %}

{% block content %}
<div>
    <h3 style="text-align: center;">{{ article_detaile.title }}</h3>
    <br>
    <h6 style="text-align: center; opacity: 50; color: #6b7280; /* grey-500">
        {% for writer in article_detaile.author.all %}
            {{ writer.name }}{% if not forloop.last %} , {% endif %}
        {% endfor %}
    </h6>
</div>
<hr>
<div class="thumbnail article-row  container">
    <img src="{{ media_url }}/{{ article_detaile.main_image }}" alt=""  class="img-300">
    <div class="abstract" style="text-align: justify;">
        <p>{{ article_detaile.abstract }}</p>
    </div>
</div>
<div class="container">
    <!-- لینک دانلود فایل PDF -->
    {% if article_detaile.pdf_name %} 
        <div style="text-align:left ; margin-top: 20px;"> 
            <a href="{{ media_url }}/{{ article_detaile.pdf_name }}" 
            class="btn btn-primary" 
            download> 
                دانلود فایل PDF 
            </a>
        </div>
    {% endif %}
</div>
<hr>
<div class="dates article-row container" style="text-align:center; margin-top:20px;">
    <p>
        <label>تاریخ ثبت:</label>
        {{ article_detaile.register_date|date:"Y/m/d" }}
    </p>
    <p>
        <label>تاریخ انتشار:</label>
        {{ article_detaile.publication_date|date:"Y/m/d" }}
    </p>
    <p>
        <label>تاریخ به‌روزرسانی:</label>
        {{ article_detaile.update_date|date:"Y/m/d" }}
    </p>
</div>
<hr>

<div class="container my-4" style="max-width: 600px;">
  <h4 class="text-center mb-3">گالری تصاویر</h4>
  <div id="articleGalleryCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      {% for img in article_detaile.articlegallery_set.all %}
        <div class="carousel-item {% if forloop.first %}active{% endif %}">
          <img src="{{ img.image.url }}" class="d-block w-100" alt="{{ img.name }}" style="max-height: 420px; object-fit: cover;">
          <div class="carousel-caption d-none d-md-block">
            <p>{{ img.name }}</p>
          </div>
        </div>
      {% empty %}
        <p>هیچ تصویری برای این مقاله ثبت نشده است.</p>
      {% endfor %}
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#articleGalleryCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">قبلی</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#articleGalleryCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">بعدی</span>
    </button>
  </div>
</div>


{% endblock content %}

templates/article_app/create.html
{% extends 'base.html' %}

{% block title %}
        صفحه ثبت نام
{% endblock title %}


{% block content %}
    <h4>{{message}}</h4>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="ثبت مقاله">


<!-- <form class="row g-3">
  <div class="col-md-6">
    <label for="inputSubject" class="form-label"> عنوان مقاله </label>
    : {{form.title}}
  </div>
  <div class="col-md-6">
    <label for="inputPassword4" class="form-label">Password</label>
    : {{form.article_group}}
  </div>
  <div class="col-12">
    <label for="inputAddress" class="form-label">Address</label>
    : {{form.main_image}}
  </div>
  <div class="col-12">
    <label for="inputAddress2" class="form-label">Address 2</label>
    : {{form.author}}
  </div>
  <div class="col-md-6">
    <label for="inputCity" class="form-label">City</label>
    : {{form.slug}}
  </div>
  <div class="col-md-4">
    <label for="inputState" class="form-label">نویسنده</label>
    <select id="inputState" class="form-select">
      <option selected>choose .....</option>
      <option>{{form.author}}</option>
      
    </select>
  </div>
  <div class="col-md-2">
    <label for="inputZip" class="form-label">Zip</label>
    <input type="text" class="form-control" id="inputZip">
  </div>
  <div class="col-12">
    <div class="form-check">
      <input class="form-check-input" type="checkbox" id="gridCheck">
      <label class="form-check-label" for="gridCheck">
        Check me out
      </label>
    </div>
  </div>
  <div class="col-12">
    <button type="submit" class="btn btn-primary">Sign in</button>
  </div>
</form> -->
    </form>
{% endblock content %}