apps/workshop/urls.py
from django.urls import path
from . import views

app_name = 'workshop'
urlpatterns = [
    path('workshop_list/',views.workshop_list,name='workshop_list'),
    path('workshop_detaile/<int:id>/',views.workshop_detaile , name='workshop_detaile'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.main.urls', namespace='main'),name='main'),
    path('places/',include('apps.places.urls',namespace='places'),name='places'),
    path('Article/',include('apps.Article.urls',namespace='Article'),name='Article'),
    path('workshop/',include('apps.workshop.urls',namespace = 'workshop'),name ='workshop')
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/workshop_app/workshop_detaile.html
{% extends 'base.html' %}

{% block title %}
جزئیات کارگاه 
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="caption">
            <h4>{{workshop_detaile.title}}</h4>
        </div>
        <hr>
       <section class="row g-3" style="margin-right: 50px; ">
                <div class="col-md-4">
                    <img src="{{workshop_detaile.main_image.url}}" alt="" class="img-300">
                </div>
            
                <div class="col-md-8">
                    <p>تاریخ برگزاری : {{workshop_detaile.date_event}}</p>
                    <p>مکان برگزاری : {{workshop_detaile.location }}</p>
                    <p>مدرس : {{workshop_detaile.teacher }}</p>
                </div>
          
       </section>
       <hr>
        <div>
            <p>اطلاعات تکمیلی  : </p>
            <p>{{workshop_detaile.description }}</p>            
        </div>
        <hr>
        <div>
            <p style="text-align: justify;">نحوه ثبت نام : {{workshop_detaile.register_way }}</p>
        </div>
        <hr>
        <div>
        <p>'گزارش کارگاه' : </p>
        <p style="text-align: justify;">{{workshop_detaile.report_text }}</p>
        </div>
    </div>
{% endblock content %}

templates/workshop_app/workshop_list.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
   لیست کارگاهها
{% endblock title %}

{% block content %}
    <h3 style="text-align: center;">لیست کارگاهها</h3>
    <div class="container">
    <table id="mytable" class="display">
        <thead>
            <tr>
                <th style="text-align: center;">عنوان کارگاه</th>
                <th style="text-align: center;"></th>                
                <th style="text-align: center;">توضیحات</th>
                <th style="text-align: center;">تاریخ برگزاری</th>
                <th style="text-align: center;">مکان برگزاری</th>
                <th style="text-align: center;">وضعیت کارگاه</th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for workshop in workshop %}
                <tr>
                    <td>{{ workshop.title }}</td>
                    <td>
                        <img src="{{media_url}}{{workshop.main_image}}" alt="" class="img-300">
                    </td>                    
                    <td style="text-align: justify;">{{ workshop.description }}</td>
                    <td>{{ workshop.date_event }}</td>
                    <td>{{ workshop.location }}</td>
                    <td>{{ workshop.workshop_statue }}</td>
                    <!-- <td>
                        <a href="{% url 'workshop:workshop_detaile' id=workshop.id %}" class="btn2">مشاهده جزییات</a>
                    </td> -->
                    <td>
                        {% if workshop.is_active and workshop.workshop_statue.id == 3 %}
                            <a href="{% url 'workshop:workshop_detaile' id=workshop.id %}" class="btn2">
                                مشاهده جزئیات
                            </a>
                        {% else %}

                            <a href="#" class="btn2 not-held">
                                مشاهده جزئیات
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>

    <!-- بارگذاری کتابخانه‌های DataTables -->
    <link rel="stylesheet" href="{% static 'css/dataTables.min.css' %}">
    <script src="{% static 'js/jquery-4.0.0.min.js' %}"></script>
    <script src="{% static 'js/dataTables.min.js' %}"></script>

    <script>
    $(document).ready(function() {
        $('#mytable').DataTable({
            language: {
                url: "{% static 'lang/fa.json' %}"
            },
            pageLength: 2,   // تعداد ردیف‌ها در هر صفحه
            lengthMenu: [5, 10, 25, 50], // گزینه‌های انتخاب تعداد
            ordering: true,   // مرتب‌سازی ستون‌ها
            searching: true   // جستجو در جدول
        });

    });
     </script>
{% endblock content %}

templates/workshop_app/workshop_list_old.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
لیست کارگاهها
{% endblock title %}

{% block content %}
  <div  class="row" style="margin-right: 50px;  text-align: justify;">
        {% for workshop in workshop %}
          <div class="col-sm-6 col-sm-4 col-lg-4">
          <div class="thumbanil">
            <img src="{{media_url}}{{workshop.main_image}}" alt="" class="img-300">
          </div>
          <br>
          <div class="caption">
            <h5>{{workshop.title}}</h5>
            <p class="description">{{workshop.description}}</p>
            <p>
              <a href="{% url 'workshop:workshop_detaile' id=workshop.id %}" class="btn1">مشاهده جزئیات</a>
            </p>
          </div>
      </div>
    {% endfor %}
  </div>
    
{% endblock content %}