apps/places/urls.py
from django.urls import path
from . import views

app_name = 'places'
urlpatterns = [
    path('history/',views.garden_history ,name='history'),
    path('section/',views.section_list , name='section'),
    path('section_detail/<int:id>/',views.section_detail ,name='section_detail'),
    path('visit_route/', views.visit_route , name = 'visit_route'),
    path('visiting_schedule/',views.visiting_schedule , name = 'visiting_schedule'),
    path('contact_view/',views.contact_view , name = 'contact_view'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.main.urls', namespace='main'),name='main'),
    path('places/',include('apps.places.urls',namespace='places'),name='places'),
    path('Article/',include('apps.Article.urls',namespace='Article'),name='Article'),
    path('workshop/',include('apps.workshop.urls',namespace = 'workshop'),name ='workshop')
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/place_app/Message_form.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="ارسال">
        <!-- <a href="{% url 'Placelist' %}">برگشت به لیست</a> -->
    </form>
{% endblock content %}

templates/place_app/contact.html
{% extends 'base.html' %}

{% block title %}
    تماس با ما
{% endblock title %}

{% block content %}
<main class="contact_main" style="margin-right: 50px;">
    <section class="contact_info">
            <h2>اطلاعات تماس</h2>            
            <p>
                <i></i>
                    تهران ، خیابان ولیعصر ، نرسیده به میدان تجریش ، کوچه بخشایش 
                <br>
                <i></i>
                    کد پستی : 19617 - 43946
                    <br>
                <i></i>
                    شماره تماس :  22705005 
            </p> 
            <h2>مسیرهای دسترسی</h2>
            <p style="text-align:justify;">
                <i></i>
                  باغ فردوس تهران از جاهای دیدنی تهران است و در خیابان ولیعصر، نرسیده به میدان تجریش قرار دارد.
                   باغ فردوس تهران، یکی از زیباترین باغ‌های تاریخی پایتخت محسوب می‌شود که با معماری چشم‌نواز عمارت مرکزی خود، درختان بلند، گل‌های رنگارنگ و آب‌نماهای زیبا، فضایی آرام و دلنشین برای گردشگران ایجاد کرده است.
            </p>
            <br>
    </section>
    <section class="contact_info">
        <h2>فرم تماس با ما</h2>
            <form class="row g-3" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">نام و نام خانوادگی</label>
             : {{form.full_name}}
            </div>

            <div class="mb-3">
            <label for="inputEmail4" class="form-label">ایمیل</label>
             : {{form.email}}
            </div>

             <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">عنوان پیام</label>
            : {{form.subject}}
            </div>

            <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">متن پیام</label>
             : {{form.mesage}}
            </div>
                
            </form>


            <input type="submit" value="ارسال پیام">
            
    </section>

</main>

{% endblock content %}

templates/place_app/history.html
{% extends 'base.html' %}

{% block title %}
    تاریخچه باغ فردس
{% endblock title %}

{% block content %}
    <div class="container">
        <h3> تاریخچه باغ</h3><hr>
        <img src="{{media_url}}/images/places/Bagh-e_Ferdows_Tajrish.jpg"
            style="width: 240px; vertical-align: middle; margin: 0 0 0 12px;" 
            alt="تصویر باغ">
        <img src="{{media_url}}/images/places/Bagatelle_roseraie_classique01.jpg"
            style="width: 240px; vertical-align: middle; margin: 0 0 0 12px;" 
            alt="تصویر باغ">
        <img src="{{media_url}}/images/places/Bagh-e_Ferdows_Tajrish.jpg"
            style="width: 240px; vertical-align: middle; margin: 0 0 0 12px;" 
            alt="تصویر باغ">
        <img src="{{media_url}}/images/places/Bagatelle_roseraie_classique01.jpg"
            style="width: 240px; vertical-align: middle; margin: 0 0 0 12px;" 
            alt="تصویر باغ">
        <!-- <img src="{{media_url}}/images/places/Bagh-e_Ferdows_Tajrish.jpg"
            style="width: 240px; vertical-align: middle; margin: 0 0 0 12px;" 
            alt="تصویر باغ"> -->
        <hr>
        <p style="text-align:justify;">
            به دستور محمدشاه قاجار، در سال ۱۲۶۴ ق، قصری برای او در نزدیکی تجریش ساخته شد؛ اما همزمان با بیماری و مرگ او قصر نیمه‌تمام ماند و وی در همان قصر نیمه‌تمام به نام محمدیه (در محل محمودیه فعلی) از دنیا رفت.

همزمان با ساخت قصر محمدیه، درباریان نزدیک به او نیز در همان حوالی اقدام به احداث باغ یا عمارت ییلاقی کردند. از جمله حسینعلی‌خان معیرالممالک باغی احداث کرد که به باغ فردوس مشهور شد.           
            
        </p>
        <p style="text-align:justify;">
            عمارت باغ فردوس در دو طبقه به سبک قاجاریه و معروف به گوش فیل بنا گذاشته شد. زمین‌های قسمت جنوبی و سراشیبی باغ نیز با سنگ‌چین‌هایی به صورت هفت قطعه مسطح و مطبق درآمد و روی هریک از قطعات، استخری با فواره‌های متعدد احداث شد. استخرها به گونه‌ای ساخته شده بودند که از فواصل دورتر، بزرگ‌تر به نظر می‌آمدند.

سپس، دوستعلی‌خان نظام‌الدوله، پسر حسین‌علی‌خان، به همت معماران اصفهانی و یزدی، ساختمانی در قسمت جنوبی باغ برپا کرد و نام آن را رشک بهشت گذاشت. پلکان و بخش‌های دیگری از ساختمان از مرمر اعلای یزد و دیوارهای داخل اتاق با کاغذهای طلایی برجسته پوشانده شده بود؛ اما پسرش دوستمحمدخان معیرالممالک اعتنای چندانی به باغ و ساختمان آن نکرد و با گذشت زمان ساختمان رو به خرابی گذاشت تا حدی که سنگ‌های مرمر آن کنده و به عمارت امیریه (مدرسه‌نظام) برده شد. بعد از آن مالکیت باغ چند بار دست به دست شد تا سرانجام در سال ۱۳۱۸ ق، در زمان سلطنت مظفرالدین شاه قاجار، محمدولی‌خان سپهسالار تنکابنی آن را از ورثه امین‌الملک خرید.

سپهسالار، علاوه بر ایجاد فواره و استخرهای مطبق، قنات باغ فردوس را نیز احیا کرد و سر دری با شکوه در مظهر قنات (میدان گاه فعلی باغ فردوس) ساخت؛ ولی به دلیل بدهی به تجارت‌خانه طومانیانس، باغ را به او داد و طومانیانس نیز باغ را در ازای بدهی به دولت رضاخان واگذار کرد. سرانجام در سال ۱۳۱۶ ش، وزارت معارف (آموزش و پرورش) آن‌جا را خرید و ساختمان را مرمت و دبیرستان شاپور تجریش را در آن تأسیس کرد

در سال ۱۳۵۰ ساختمان موجود در باغ به مرکز فرهنگی و هنری و نمایشگاهی تبدیل شد و پس از انقلاب نیز در اختیار وزارت فرهنگ و ارشاد اسلامی قرار گرفت.

مساحت باغ فردوس ۲۰۰۰۰ متر مربع و طول آن ۲۸۰ متر و شیب آن از شمال غربی به جنوب شرقی است.

هم‌چنین، محمود افشار یزدی در سال ۱۳۱۶، قسمتی از باغ و ساختمان اندرونی را که حدود ۶۰۰۰ متر مربع بود، خرید و به تدریج با خریدن قطعات اطراف، مساحت باغ را به ۱۲۰۰۰ متر مربع رسانید. سپس در سال ۱۳۳۷، باغ و ساختمان‌های داخل آن را وقف امور فرهنگی کرد؛ از جمله در سال ۱۳۵۲ قسمتی از آن برای استقرار مؤسسه لغت نامه دهخدا و مؤسسه باستان‌شناسی به دانشگاه تهران واگذار شد که هم‌چنان دایر است.
        </p>
    </div>
{% endblock content %}

templates/place_app/section.html
{% extends 'base.html' %}

{% block title %}
بخش های باغ 
{% endblock title %}

{% block content %}
  <div class="row" style="margin-right: 50px;  text-align: justify;">
        {% for place in section %}

      <div class="col-sm-6 col-sm-4 col-lg-4">
          <div class="thumbanil">
            <img src="{{media_url}}/{{place.image}}" alt="" class="img-300">
          </div>
          <br>
          <div class="caption">
            <h4>{{place.title}}</h4>
            <p class="description">{{place.description}}</p>
            <p>
              <a href="{% url 'places:section_detail' id=place.id %}" class="btn1">مشاهده جزئیات</a>
            </p>
          </div>
      </div>
    {% endfor %}
  </div>
{% endblock content %}

templates/place_app/section_detail.html
{% extends 'base.html' %}

{% block title %}
بخش های باغ 
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="caption">
            <h4>{{section_detail.title}}</h4>
        </div>
        <hr>
        <div class="thumbanil">
                <img src="{{media_url}}/{{section_detail.image}}" alt="" class="img-300">
        </div>
        <br>
        <div>
            <p style="text-align: justify;">{{section_detail.ruls}}</p>
        </div>
        <hr>
        <div>
            <p>روزهای بازدید : {{section_detail.visiting_day}}</p>
        </div>
        <hr>
        <div>
            <p>ساعت بازدید : {{section_detail.visiting_hour }}</p>
        </div>
    </div>
{% endblock content %}

templates/place_app/visiting_schedule.html
{% extends 'base.html' %}

{% block title %}
برنامه بازدید 
{% endblock title %}

{% block content %}
    <h5> زمان بازدید :</h5>
    <hr>
    <ul>
        {% for place in place %}
        <li>
             <strong>{{place.title}}</strong> : <span class="value1">{{place.visiting_day}}</span>  |
                                                <span class="value1">{{place.visiting_hour}}</span> 
                                                             
        </li>
        {% endfor %}
    </ul>
    <br>
    <h5> بهای بلیط : </h5>
    <hr>
    <ul>
        {% for price in price %}
        <li>
            <span>بهای بلیط </span>
             <strong>{{price.place}}</strong> 
             <span>برای بازدید کننده</span>
             <span class="value2">{{price.visitor_type}}</span>  
             <span> : </span>
             <span class="value1">{{price.price}}</span>
             <span> ریال </span>
                                                             
        </li>
        {% endfor %}
    </ul>
{% endblock content %}